### ISSUE TITLE
Make AsyncQueue public?

### ISSUE THREAD

**Issue by novabyte** [deniszykov/WebSocketListener#23]
@deniszykov Do you think you could update `AsyncQueue<T>` to be public? It's a useful class I want to use in the rest of my [code](https://github.com/heroiclabs/nakama-dotnet) for a project. Is there a specific reason it's kept as internal?

**Comment by deniszykov** [comment]
Hi @novabyte! It is internal because it is not supposed to be used from outside of the library. There is a multiple reasons for this:
1) Any public classes can't be easily replaced/removed without introducing breaking changes.
2) Providing async collections is not main purpose of this library. 
3) They are designed for this particular case and there is no plans to extent them for general usage.

Anyway. You take those classes for your project. License is MIT.

p.s. PingQueue and TimedQueue are public by mistake.

**Comment by novabyte** [comment]
Ok, a shame but understood.
